name: Build and run tests

on:
  push

env:
  DOTNET_SDK_VERSION: '9.0.x'
  DOTNET_TFM: 'net9.0'

jobs:
  build-and-test:
    runs-on: windows-latest
    steps:
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@v4

      - name: Setup DotNet ${{ env.DOTNET_SDK_VERSION }} Environment
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ env.DOTNET_SDK_VERSION }}

      - name: 'Build .NET Projects'
        shell: pwsh
        run: |
          dotnet build --configuration Release
          dotnet test --configuration Release -p:CollectCoverage=true -p:CoverletOutputFormat=opencover --no-restore --verbosity normal
          
          dir -recurse

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4.0.1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: lassevk/difflib